server:
  port: 9527

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.181.10:8848
        group: dev1
        namespace: public #8dfdcc4a-26e3-4514-b1ad-4f3ac3e939d4
        username: nacos
        password: nacos
    gateway:
      routes:
        # ??ID????????????????????
        - id: cloud-test-provider
          # ???????????? (???????)
          uri: lb://test
          # ?????????????????????
          predicates:
            # ??????????
          - Path=/test/**
